spring:
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# -- contextual colors ----------------------------------------
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED