CREATE TABLE "students"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "last_name"      varchar NOT NULL,
    "first_name"     varchar NOT NULL,
    "surname"        varchar,
    "year"           int     NOT NULL,
    "form_education" varchar NOT NULL,
    "group"          int     NOT NULL
);

CREATE TABLE "subject"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar NOT NULL,
    "department" varchar NOT NULL
);

CREATE TABLE "study_plan"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "subject_id"     int,
    "semeser"        int     NOT NULL,
    "hours"          int     NOT NULL,
    "reporting_form" varhcar NOT NULL
);

CREATE TABLE "academic_performance"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "student_id" int,
    "subject_id" int,
    "grade"      int NOT NULL
);

CREATE UNIQUE INDEX ON "subject" ("name", "department");

ALTER TABLE "study_plan"
    ADD FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE "academic_performance"
    ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "academic_performance"
    ADD FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");
