-- liquibase formatted sql

--changeset greenblat17:1
CREATE TABLE IF NOT EXISTS "students"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "last_name"      varchar NOT NULL,
    "first_name"     varchar NOT NULL,
    "surname"        varchar,
    "year"           int     NOT NULL,
    "form_education" varchar NOT NULL,
    "group"          int     NOT NULL
);
--rollback DROP TABLE students

--changeset greenblat17:2
CREATE TABLE IF NOT EXISTS "subject"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"       varchar NOT NULL,
    "department" varchar NOT NULL
);
--rollback DROP TABLE subject

--changeset greenblat17:3
CREATE TABLE IF NOT EXISTS  "study_plan"
(
    "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "subject_id"     int,
    "semeser"        int     NOT NULL,
    "hours"          int     NOT NULL,
    "reporting_form" varchar NOT NULL
);
--rollback DROP TABLE study_plan

--changeset greenblat17:4
CREATE TABLE IF NOT EXISTS  "academic_performance"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "student_id" int,
    "subject_id" int,
    "grade"      int NOT NULL
);
--rollback DROP TABLE academic_performance

--changeset greenblat17:5
CREATE TABLE IF NOT EXISTS  "users"
(
    "id"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar NOT NULL UNIQUE,
    "password" varchar NOT NULL,
    "role"     varchar NOT NULL
);
--rollback DROP TABLE users

--changeset greenblat17:6
CREATE UNIQUE INDEX ON "subject" ("name", "department");

ALTER TABLE "study_plan"
    ADD FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE "academic_performance"
    ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "academic_performance"
    ADD FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");
